export { LoginScreen as ScreenLogin } from "./Login"
export { RegisterScreen as ScreenRegister } from "./Register"
export { PerfilScreen as ScreenPerfil } from "./Perfil"
export { ListVinylRecordsScreen as ScreenListVinylRecords } from "./Vinyl/ListVinylRecords"
export { VinylRecordDetailsScreen as ScreenVinylRecordDetails } from "./Vinyl/VinylRecordDetails"
export { RegisterVinylRecordScreen as ScreenRegisterVinylRecord } from "./Vinyl/RegisterVinylRecord"
export { EditVinylRecordScreen as ScreenEditVinylRecord } from "./Vinyl/EditVinylRecord"
export { BorrowMapScreen as ScreenBorrowMap } from "./Vinyl/BorrowMapScreen"
export { CameraScreen as ScreenPhoto } from "./Camera"
export { ImagemScreen as  ScreenImagem} from "./Imagens"
export {VideoScreen as ScreenVideo} from "./Video"
export {LocationMap as ScreenLocation} from "./LocationMap"
export {LocationScreen as ScreenMapLocation} from "./Location"